export interface FitSwitch {
  WISO_000_MESSAGE_TYPE: String;
  WISO_003_PROCESSINGCODE: String;
  WISO_018_MERCHANTTYPE: String;
  WISO_024_NETWORKID: String;
  WISO_007_TRANSDATETIME: String;
  WISO_002_PAN: String;
}
